/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/fighter/update-boxing-ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scrape And Save Boxing Ranks */
        get: operations["scrape_and_save_boxing_ranks_api_fighter_update_boxing_ranks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fighter/update-boxing-fight-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scrape And Save Boxing Fight Cards */
        get: operations["scrape_and_save_boxing_fight_cards_api_fighter_update_boxing_fight_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fighter/generate-avatars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Fighter Avatars */
        post: operations["generate_fighter_avatars_api_fighter_generate_avatars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fighter/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Featured Fighters */
        get: operations["get_featured_fighters_api_fighter_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvatarGenerationResult */
        AvatarGenerationResult: {
            /** Updated */
            updated: string[];
            /** Skipped */
            skipped: string[];
        };
        /** BoutRead */
        BoutRead: {
            /**
             * Id
             * Format: uuid4
             * @description The ID of the object.
             */
            id: string;
            /** Boutorder */
            boutOrder?: number | null;
            /** Istitlefight */
            isTitleFight: boolean;
            redCorner: components["schemas"]["FighterRead"];
            blueCorner: components["schemas"]["FighterRead"];
        };
        /**
         * FeaturedCollection
         * @enum {string}
         */
        FeaturedCollection: "popular_fighters";
        /** FeaturedFighterRead */
        FeaturedFighterRead: {
            /**
             * Id
             * Format: uuid4
             * @description The ID of the object.
             */
            id: string;
            /** Name */
            name: string;
            /** Avatarurl */
            avatarUrl?: string | null;
        };
        /** FightCardRead */
        FightCardRead: {
            /**
             * Id
             * Format: uuid4
             * @description The ID of the object.
             */
            id: string;
            /** Eventname */
            eventName?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Eventdate
             * Format: date-time
             */
            eventDate: string;
            /**
             * Bouts
             * @default []
             */
            bouts: components["schemas"]["BoutRead"][];
        };
        /** FighterRead */
        FighterRead: {
            /**
             * Id
             * Format: uuid4
             * @description The ID of the object.
             */
            id: string;
            /** Name */
            name: string;
            /** Nickname */
            nickname?: string | null;
            /** Age */
            age?: number | null;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Draws */
            draws?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RankRead */
        RankRead: {
            rankType: components["schemas"]["RankType"];
            /** Position */
            position: number | null;
            /** Fightername */
            fighterName: string;
            /** Weightclassname */
            weightClassName: string;
            /** Organizationname */
            organizationName: string;
        };
        /**
         * RankType
         * @enum {string}
         */
        RankType: "champion" | "interim_champion" | "champion_in_recess" | "contender";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scrape_and_save_boxing_ranks_api_fighter_update_boxing_ranks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update boxing ranks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankRead"][];
                };
            };
        };
    };
    scrape_and_save_boxing_fight_cards_api_fighter_update_boxing_fight_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update boxing fight cards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightCardRead"][];
                };
            };
        };
    };
    generate_fighter_avatars_api_fighter_generate_avatars_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generate Ghibli avatars for fighters missing one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarGenerationResult"];
                };
            };
        };
    };
    get_featured_fighters_api_fighter_featured_get: {
        parameters: {
            query?: {
                collection?: components["schemas"]["FeaturedCollection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List featured fighters for a curated collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedFighterRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const featuredCollectionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["FeaturedCollection"]> = ["popular_fighters"];
export const rankTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RankType"]> = ["champion", "interim_champion", "champion_in_recess", "contender"];
