"""Initial migration

Revision ID: 613bf616bced
Revises: 
Create Date: 2025-03-23 23:34:25.014398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613bf616bced'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.ENUM('UFC', 'WBO', 'WBC', 'IBF', 'WBA', name='fightorganizationenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fight_organizations_id'), 'fight_organizations', ['id'], unique=False)
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighters_id'), 'fighters', ['id'], unique=False)
    op.create_index(op.f('ix_fighters_name'), 'fighters', ['name'], unique=False)
    op.create_table('weight_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('upper_limit', sa.Integer(), nullable=True),
    sa.Column('lower_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_classes_id'), 'weight_classes', ['id'], unique=False)
    op.create_table('fighter_fight_organization_association',
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('fight_organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fight_organization_id'], ['fight_organizations.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('fighter_id', 'fight_organization_id')
    )
    op.create_table('fighter_weight_class_association',
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('weight_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ),
    sa.PrimaryKeyConstraint('fighter_id', 'weight_class_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fighter_weight_class_association')
    op.drop_table('fighter_fight_organization_association')
    op.drop_index(op.f('ix_weight_classes_id'), table_name='weight_classes')
    op.drop_table('weight_classes')
    op.drop_index(op.f('ix_fighters_name'), table_name='fighters')
    op.drop_index(op.f('ix_fighters_id'), table_name='fighters')
    op.drop_table('fighters')
    op.drop_index(op.f('ix_fight_organizations_id'), table_name='fight_organizations')
    op.drop_table('fight_organizations')
    # ### end Alembic commands ###
