"""remove fight_card_id from fighters table

Revision ID: 955ba92d5011
Revises: d6d7f88fd803
Create Date: 2025-04-01 00:14:37.238861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955ba92d5011'
down_revision: Union[str, None] = 'd6d7f88fd803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fighters_fight_card_id_fkey', 'fighters', type_='foreignkey')
    op.drop_column('fighters', 'fight_card_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('fight_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fighters_fight_card_id_fkey', 'fighters', 'fight_cards', ['fight_card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
