"""remove association tables between weight class, fighter, organizations

Revision ID: c456bf837b23
Revises: b6b2c6c4e8f2
Create Date: 2025-03-29 19:39:33.944994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c456bf837b23'
down_revision: Union[str, None] = 'b6b2c6c4e8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fighter_fight_organization_association')
    op.drop_table('fighter_weight_class_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighter_weight_class_association',
    sa.Column('fighter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_champ', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name='fighter_weight_class_association_fighter_id_fkey'),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], name='fighter_weight_class_association_weight_class_id_fkey'),
    sa.PrimaryKeyConstraint('fighter_id', 'weight_class_id', name='fighter_weight_class_association_pkey')
    )
    op.create_table('fighter_fight_organization_association',
    sa.Column('fighter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fight_organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fight_organization_id'], ['fight_organizations.id'], name='fighter_fight_organization_associati_fight_organization_id_fkey'),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name='fighter_fight_organization_association_fighter_id_fkey'),
    sa.PrimaryKeyConstraint('fighter_id', 'fight_organization_id', name='fighter_fight_organization_association_pkey')
    )
    # ### end Alembic commands ###
