"""added fight_card_fighters association table

Revision ID: d6d7f88fd803
Revises: ad80a774081b
Create Date: 2025-04-01 00:12:40.435795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d7f88fd803'
down_revision: Union[str, None] = 'ad80a774081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_card_fighters',
    sa.Column('fight_card_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fight_card_id'], ['fight_cards.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('fight_card_id', 'fighter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fight_card_fighters')
    # ### end Alembic commands ###
