"""change FightCard column name (broadcasting_network to network)

Revision ID: e86f7d01ab66
Revises: 128fa20597b8
Create Date: 2025-04-07 23:57:19.685574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86f7d01ab66'
down_revision: Union[str, None] = '128fa20597b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight_cards', sa.Column('network', sa.String(), nullable=True))
    op.drop_column('fight_cards', 'broadcasting_network')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fight_cards', sa.Column('broadcasting_network', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fight_cards', 'network')
    # ### end Alembic commands ###
