"""initial schema

Revision ID: c435cee8315e
Revises: 
Create Date: 2026-05-17 21:46:36.451885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c435cee8315e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$ BEGIN CREATE TYPE combatsport AS ENUM ('boxing', 'mma'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE ranktype AS ENUM ('champion', 'interim_champion', 'champion_in_recess', 'contender'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    op.create_table('fight_cards',
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fight_cards_pkey')),
    sa.UniqueConstraint('event_name', 'event_date', name='uq_fight_card_event')
    )
    op.create_index(op.f('ix_fight_cards_created_at'), 'fight_cards', ['created_at'], unique=False)
    op.create_table('fight_organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sport', postgresql.ENUM('boxing', 'mma', name='combatsport', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fight_organizations_pkey')),
    sa.UniqueConstraint('name', name='uq_fight_organizations_name')
    )
    op.create_index(op.f('ix_fight_organizations_created_at'), 'fight_organizations', ['created_at'], unique=False)
    op.create_table('fighters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fighters_pkey'))
    )
    op.create_index(op.f('ix_fighters_created_at'), 'fighters', ['created_at'], unique=False)
    op.create_index(op.f('ix_fighters_name'), 'fighters', ['name'], unique=True)
    op.create_table('weight_classes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pounds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weight_classes_pkey')),
    sa.UniqueConstraint('name', name='uq_weight_classes_name')
    )
    op.create_index(op.f('ix_weight_classes_created_at'), 'weight_classes', ['created_at'], unique=False)
    op.create_table('bouts',
    sa.Column('fight_card_id', sa.Uuid(), nullable=False),
    sa.Column('red_corner_id', sa.Uuid(), nullable=False),
    sa.Column('blue_corner_id', sa.Uuid(), nullable=False),
    sa.Column('bout_order', sa.Integer(), nullable=True),
    sa.Column('is_title_fight', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blue_corner_id'], ['fighters.id'], name=op.f('bouts_blue_corner_id_fkey')),
    sa.ForeignKeyConstraint(['fight_card_id'], ['fight_cards.id'], name=op.f('bouts_fight_card_id_fkey')),
    sa.ForeignKeyConstraint(['red_corner_id'], ['fighters.id'], name=op.f('bouts_red_corner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bouts_pkey'))
    )
    op.create_index(op.f('ix_bouts_created_at'), 'bouts', ['created_at'], unique=False)
    op.create_table('ranks',
    sa.Column('fighter_id', sa.Uuid(), nullable=False),
    sa.Column('weight_class_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rank_type', postgresql.ENUM('champion', 'interim_champion', 'champion_in_recess', 'contender', name='ranktype', create_type=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('ranks_fighter_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['fight_organizations.id'], name=op.f('ranks_organization_id_fkey')),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], name=op.f('ranks_weight_class_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ranks_pkey')),
    sa.UniqueConstraint('weight_class_id', 'organization_id', 'position', name='uq_rank_contender_position')
    )
    op.create_index(op.f('ix_ranks_created_at'), 'ranks', ['created_at'], unique=False)
    op.create_index('uq_rank_champion_type', 'ranks', ['weight_class_id', 'organization_id', 'rank_type'], unique=True, postgresql_where=sa.text("rank_type != 'contender'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rank_champion_type', table_name='ranks', postgresql_where=sa.text("rank_type != 'contender'"))
    op.drop_index(op.f('ix_ranks_created_at'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_bouts_created_at'), table_name='bouts')
    op.drop_table('bouts')
    op.drop_index(op.f('ix_weight_classes_created_at'), table_name='weight_classes')
    op.drop_table('weight_classes')
    op.drop_index(op.f('ix_fighters_name'), table_name='fighters')
    op.drop_index(op.f('ix_fighters_created_at'), table_name='fighters')
    op.drop_table('fighters')
    op.drop_index(op.f('ix_fight_organizations_created_at'), table_name='fight_organizations')
    op.drop_table('fight_organizations')
    op.drop_index(op.f('ix_fight_cards_created_at'), table_name='fight_cards')
    op.drop_table('fight_cards')
    op.execute("DROP TYPE IF EXISTS ranktype")
    op.execute("DROP TYPE IF EXISTS combatsport")
    # ### end Alembic commands ###
