"""add featured_fighters table

Revision ID: 7424d053a53f
Revises: b7c4e5f6a2d1
Create Date: 2026-06-15 21:01:37.625584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7424d053a53f'
down_revision: Union[str, None] = 'b7c4e5f6a2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_fighters',
    sa.Column('fighter_id', sa.Uuid(), nullable=False),
    sa.Column('collection', postgresql.ENUM('popular_fighters', name='featuredcollection'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('featured_fighters_fighter_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('featured_fighters_pkey')),
    sa.UniqueConstraint('collection', 'fighter_id', name='uq_featured_collection_fighter')
    )
    op.create_index(op.f('ix_featured_fighters_collection'), 'featured_fighters', ['collection'], unique=False)
    op.create_index(op.f('ix_featured_fighters_created_at'), 'featured_fighters', ['created_at'], unique=False)
    op.create_index('uq_featured_collection_position', 'featured_fighters', ['collection', 'position'], unique=True, postgresql_where=sa.text('position IS NOT NULL'))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_featured_collection_position', table_name='featured_fighters', postgresql_where=sa.text('position IS NOT NULL'))
    op.drop_index(op.f('ix_featured_fighters_created_at'), table_name='featured_fighters')
    op.drop_index(op.f('ix_featured_fighters_collection'), table_name='featured_fighters')
    op.drop_table('featured_fighters')
    # ### end Alembic commands ###
