"""initial migration

Revision ID: 0dc521d6835a
Revises: 
Create Date: 2026-05-17 12:33:03.925666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc521d6835a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_cards',
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fight_cards_pkey'))
    )
    op.create_index(op.f('ix_fight_cards_created_at'), 'fight_cards', ['created_at'], unique=False)
    op.create_table('fight_organizations',
    sa.Column('name', postgresql.ENUM('UFC', 'WBO', 'WBC', 'IBF', 'WBA', name='fightorganizationenum'), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fight_organizations_pkey'))
    )
    op.create_index(op.f('ix_fight_organizations_created_at'), 'fight_organizations', ['created_at'], unique=False)
    op.create_table('fighters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fighters_pkey'))
    )
    op.create_index(op.f('ix_fighters_created_at'), 'fighters', ['created_at'], unique=False)
    op.create_index(op.f('ix_fighters_name'), 'fighters', ['name'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone_no', name=op.f('users_phone_no_key')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weight_classes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pounds', sa.Integer(), nullable=True),
    sa.Column('kilos', sa.Integer(), nullable=True),
    sa.Column('upper_limit', sa.Integer(), nullable=True),
    sa.Column('lower_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weight_classes_pkey'))
    )
    op.create_index(op.f('ix_weight_classes_created_at'), 'weight_classes', ['created_at'], unique=False)
    op.create_table('fight_card_fighters',
    sa.Column('fight_card_id', sa.Uuid(), nullable=False),
    sa.Column('fighter_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fight_card_id'], ['fight_cards.id'], name=op.f('fight_card_fighters_fight_card_id_fkey')),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('fight_card_fighters_fighter_id_fkey')),
    sa.PrimaryKeyConstraint('fight_card_id', 'fighter_id', name=op.f('fight_card_fighters_pkey'))
    )
    op.create_table('ranks',
    sa.Column('rank', sa.Double(), nullable=False),
    sa.Column('fighter_id', sa.Uuid(), nullable=False),
    sa.Column('weight_class_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], name=op.f('ranks_fighter_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['fight_organizations.id'], name=op.f('ranks_organization_id_fkey')),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], name=op.f('ranks_weight_class_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ranks_pkey')),
    sa.UniqueConstraint('rank', 'weight_class_id', 'organization_id', name=op.f('ranks_rank_weight_class_id_organization_id_key'))
    )
    op.create_index(op.f('ix_ranks_created_at'), 'ranks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranks_created_at'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_table('fight_card_fighters')
    op.drop_index(op.f('ix_weight_classes_created_at'), table_name='weight_classes')
    op.drop_table('weight_classes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fighters_name'), table_name='fighters')
    op.drop_index(op.f('ix_fighters_created_at'), table_name='fighters')
    op.drop_table('fighters')
    op.drop_index(op.f('ix_fight_organizations_created_at'), table_name='fight_organizations')
    op.drop_table('fight_organizations')
    op.drop_index(op.f('ix_fight_cards_created_at'), table_name='fight_cards')
    op.drop_table('fight_cards')
    # ### end Alembic commands ###
